### ISSUE TITLE
Amazing: from 45Mo to 5Mo

### ISSUE THREAD

**Issue by pascalandy** [productionwentdown/caddy#1]
I can't believe it:

![screen shot 2018-12-06 at 2 31 25 pm](https://user-images.githubusercontent.com/6694151/49607374-c4955680-f963-11e8-88fe-6d9198d922ca.jpg)

Good job on this!

**Comment by serverwentdown** [comment]
Thanks! (but no issues please 😄)

**Comment by pascalandy** [comment]
Sure, but I could not reach you otherwise.

> Thanks! (but no issues please 😄)
